version: '3.5'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/run/postgresql/data'
  web:
    depends_on:
      - 'postgres'
    build:
      context: .
    ports:
      - '3000:3000'
    command: docker/entrypoint.sh
    volumes:
      - '.:/nobe-test'
      - bundle:/bundle
      - cache:/cache
    env_file:
      - '.env.docker'
volumes:
  postgres_data:
  bundle:
  cache:
